openapi: 3.0.0
servers:
  - url: 'https://localhost:5000/'
    description: Nodejs server
info:
  title: External process communication
  description: Specification of communication between external process and CobiGen
  version: 1.0.0
  x-rootpackage: com.devonfw.poc
paths:
  /processmanagement/inputReader/isValidInput/:
    post:
      description: Returns true or false whether it is a valid input for generation
      requestBody:
        $ref: '#/components/requestBodies/File'
      operationId: isValidInput
      responses:
        '200':
          description: Returns true or false whether it is a valid input for generation
          content:
            application/json:
              schema:
                type: object
                properties:
                  isValidInput:
                    type: boolean
        '404':
          description: Not found
  /processmanagement/inputReader/createModel/:
    post:
      requestBody:
        $ref: '#/components/requestBodies/File'
      operationId: createModel
      responses:
        '200':
          description: Returns data model in JSON format
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Model'
        '404':
          description: Not found
  /processmanagement/inputReader/getInputObjects/:
    post:
      description: Requesting models for each input object found at the input file
      requestBody:
        $ref: '#/components/requestBodies/File'
      operationId: getInputObjects
      responses:
        '200':
          description: Returns array of models in JSON format
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Models'
        '404':
          description: Not found
  /processmanagement/inputReader/getInputObjectsRecursively/:
    post:
      description: Requesting models for each input object found at the input file (recursively)
      requestBody:
        $ref: '#/components/requestBodies/File'
      operationId: getInputObjectsRecursively
      responses:
        '200':
          description: Returns array of models in JSON format
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Models'
        '404':
          description: Not found
  /processmanagement/inputReader/read/:
    post:
      description: Returns a valid input for CobiGen in JSON format
      requestBody:
        $ref: '#/components/requestBodies/File'
      operationId: read
      responses:
        '200':
          description: Returns a valid input for CobiGen in JSON format
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Model'
        '404':
          description: Not found
  /processmanagement/matcher/matches/:
    post:
      description:  Checks whether the given matcher matches the sent input
      requestBody:
        $ref: '#/components/requestBodies/Matcher'
      operationId: matches
      responses:
        '200':
          description: Returns true or false whether it matches
          content:
            application/json:
              schema:
                type: object
                properties:
                  matches:
                    type: boolean
        '404':
          description: Not found
  /processmanagement/matcher/resolveVariables/:
    post:
      description:  resolve all given variable assignments
      requestBody:
        $ref: '#/components/requestBodies/File'
      operationId: resolveVariables
      responses:
        '200':
          description: Returns resolved variables
          content:
            application/json:
              schema:
                type: object
                properties:
                  isValidInput:
                    type: boolean
        '404':
          description: Not found
  /processmanagement/merger/merge/:
    post:
      description:  Merges two files and returns the result
      requestBody:
        $ref: '#/components/requestBodies/Merger'
      operationId: merge
      responses:
        '200':
          description: Returns resolved variables
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Not found
components:
    schemas:
        Models:
          x-component: processmanagement
          description: Array of models
          type: array
          items:
            type: object
            properties:
              Field:
                $ref: '#/components/schemas/Model'
        Model:
          x-component: processmanagement
          description: Data model of the input file
          type: object
          properties:
            fileType:
              type: string
              maxLength: 30
              minLength: 1
              uniqueItems: true
            fileName:
              type: string
              maxLength: 30
              minLength: 1
              uniqueItems: true
            Fields:
              $ref: '#/components/schemas/Fields'
            Imports: 
              $ref: '#/components/schemas/Imports'
        Fields:
          x-component: processmanagement
          description: Array of fields
          type: array
          items:
            type: object
            properties:
              Field:
                $ref: '#/components/schemas/Field'
        Field:
          x-component: processmanagement
          description: Field
          type: object
          properties:
            fieldName:
                type: string
            fieldType:
                type: string
        Imports:
          x-component: processmanagement
          description: Array of imports
          type: array
          items:
            type: object
            properties:
              Import:
                $ref: '#/components/schemas/Import'
        Import:
          x-component: processmanagement
          description: Field
          type: object
          properties:
            importValue:
                type: string
        File:
          x-component: processmanagement
          description: Input file
          type: object
          properties:
            filePath:
              type: string
        Matcher:
          x-component: processmanagement
          description: Matcher properties
          type: object
          properties:
            inputToMatch:
              type: object
            type:
              type: string
            value:
              type: string
            accumulationType:
              type: string
        VariableAssignment:
          x-component: processmanagement
          description: Matcher properties
          type: object
          properties:
            inputToResolve:
              type: string
            type:
              type: string
            key:
              type: string
            value:
              type: string
        Merger:
          x-component: processmanagement
          description: Merger properties
          type: object
          properties:
            baseContent:
              type: string
            patchContent:
              type: string
            patchOverrides:
              type: boolean


    requestBodies:
        Model:
          description: Data model of the file in JSON format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Model'
          required: true
        Models:
          description: Array of models (JSON format)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Models'
          required: true
        File:
          description: Input file path
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/File'
          required: true
        Matcher:
          description: Matcher properties
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Matcher'
          required: true
        VariableAssignment:
          description: Variable assignment properties
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VariableAssignment'
          required: true
        Merger:
          description: Objects to be merged
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Merger'
          required: true
 